### ISSUE TITLE
pr

### ISSUE THREAD

**Issue by jonschlinkert** [tunnckoCore/is-installed#2]
Holy crap, I just created [this code](https://gist.github.com/jonschlinkert/f4457fe39070894ca8637c85f59995cd) before I checked if this existed (I thought I did!). 

It's crazy how similar that is to `detect-installed`. Anyway, I think there are some differences in mine that I'd love to see implemented here or in detect-installed. Honestly it seems like you have detect-installed and is-installed backwards. It seems like this lib should just return true or false, but detect-installed would check both global and local using this lib.

I can do a pr with the code I wrote to this lib. thoughts?

**Comment by tunnckoCore** [comment]
Hey hay haha. I can come to this in one two days. I have both of this in my kanban and I also don't like how they are currently. Yea, looks like a good idea to have option to get the metadata if exist. hm.

**Comment by tunnckoCore** [comment]
Yea, okey, send a PR :) I'll merge through web when i can.
